<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <RootNamespace>Rhizine.WPF</RootNamespace>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ImplicitUsings>enable</ImplicitUsings>
	<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
	<Platforms>AnyCPU;x64</Platforms>
	<AnalysisLevel>latest-recommended</AnalysisLevel>
	<Title>Rhizine.WPF</Title>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <WarningLevel>9999</WarningLevel>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <WarningLevel>9999</WarningLevel>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <WarningLevel>9999</WarningLevel>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <WarningLevel>9999</WarningLevel>
  </PropertyGroup>
  
  <ItemGroup>
    <Compile Remove="Resources\LoadingIndicators.WPF\**" />
    <Compile Remove="Services\Interfaces\**" />
    <EmbeddedResource Remove="Resources\LoadingIndicators.WPF\**" />
    <EmbeddedResource Remove="Services\Interfaces\**" />
    <None Remove="Resources\LoadingIndicators.WPF\**" />
    <None Remove="Services\Interfaces\**" />
    <Page Remove="Resources\LoadingIndicators.WPF\**" />
    <Page Remove="Services\Interfaces\**" />
  </ItemGroup>
  
  <ItemGroup>
    <Compile Remove="Models\Interfaces\INavigationAware.cs" />
    <Compile Remove="Helpers\AsyncResultProvider.cs" />
    <Compile Remove="Helpers\IActivationHandler.cs" />
    <Compile Remove="Helpers\IResultProvider.cs" />
    <Compile Remove="Models\AppTheme.cs" />
    <Compile Remove="Models\IEntity.cs" />
    <Compile Remove="Models\IRepository.cs" />
    <Compile Remove="Models\LoggingMessages.cs" />
    <Compile Remove="Models\Repository.cs" />
    <Compile Remove="Models\SampleCompany.cs" />
    <Compile Remove="Models\SampleOrder.cs" />
    <Compile Remove="Models\SampleOrderDetail.cs" />
    <Compile Remove="Services\AsyncLoggingService.cs" />
    <Compile Remove="Services\CachingService.cs" />
    <Compile Remove="Services\DataService.cs" />
    <Compile Remove="Services\FileService.cs" />
    <Compile Remove="Services\LoggingService.cs" />
    <Compile Remove="Services\PageService.cs" />
    <Compile Remove="Services\SampleDataService.cs" />
    <Compile Remove="Services\SystemService.cs" />
  </ItemGroup>
  
  <ItemGroup>
    <Page Remove="Styles\Themes\Default.xaml" />
  </ItemGroup>
  
  <ItemGroup>
    <Compile Include="Services\Interfaces\IFlyoutService.cs" />
    <Compile Include="Services\Interfaces\IPopupService.cs" />
    <Compile Include="Services\Interfaces\IToastNotificationsService.cs" />
    <Compile Include="Services\Interfaces\IWindowManagerService.cs" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageReference Include="CommunityToolkit.WinUI.Notifications" Version="7.1.2" />
    <PackageReference Include="MahApps.Metro" Version="2.4.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.4" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Shell.Framework" Version="17.9.37000" />
    <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.9.28">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2478.35" />
    <PackageReference Include="Serilog" Version="3.1.1" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="2.3.0" />
    <PackageReference Include="Serilog.Enrichers.Thread" Version="3.1.0" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="8.0.0" />
    <PackageReference Include="Serilog.Sinks.Async" Version="1.5.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="5.0.1" />
    <PackageReference Include="Serilog.Sinks.Debug" Version="2.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
    <PackageReference Include="Serilog.Sinks.OpenObserve-KKP" Version="1.0.2" />
    <PackageReference Include="WpfAnalyzers" Version="4.1.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\Interfaces\" />
    <Folder Include="Resources\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rhizine.Core\Rhizine.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Remove="C:\Users\Main\.nuget\packages\microsoft.visualstudio.sdk.analyzers\16.10.10\build\AdditionalFiles\vs-threading.LegacyThreadSwitchingMembers.txt" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Remove="C:\Users\Main\.nuget\packages\microsoft.visualstudio.threading.analyzers\17.8.14\build\AdditionalFiles\vs-threading.LegacyThreadSwitchingMembers.txt" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Remove="C:\Users\Main\.nuget\packages\microsoft.visualstudio.sdk.analyzers\16.10.10\build\AdditionalFiles\vs-threading.MainThreadAssertingMethods.txt" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Remove="C:\Users\Main\.nuget\packages\microsoft.visualstudio.threading.analyzers\17.8.14\build\AdditionalFiles\vs-threading.MainThreadAssertingMethods.txt" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Remove="C:\Users\Main\.nuget\packages\microsoft.visualstudio.sdk.analyzers\16.10.10\build\AdditionalFiles\vs-threading.MainThreadSwitchingMethods.txt" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Remove="C:\Users\Main\.nuget\packages\microsoft.visualstudio.threading.analyzers\17.8.14\build\AdditionalFiles\vs-threading.MainThreadSwitchingMethods.txt" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Remove="C:\Users\Main\.nuget\packages\microsoft.visualstudio.sdk.analyzers\16.10.10\build\AdditionalFiles\vs-threading.MembersRequiringMainThread.txt" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Remove="C:\Users\Main\.nuget\packages\microsoft.visualstudio.threading.analyzers\17.8.14\build\AdditionalFiles\vs-threading.MembersRequiringMainThread.txt" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Remove="C:\Users\Main\.nuget\packages\microsoft.visualstudio.sdk.analyzers\16.10.10\build\AdditionalFiles\vs-threading.MembersRequiringMainThread.txt" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Remove="C:\Users\Main\.nuget\packages\microsoft.visualstudio.threading.analyzers\17.8.14\build\AdditionalFiles\vs-threading.MembersRequiringMainThread.txt" />
  </ItemGroup>
</Project>
