<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
	  <RootNamespace>Rhizine.Core</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>Rhizine.Core</Title>
    <Authors>Dillion Lowry</Authors>
    <Copyright>MIT License Copyright (c) 2023 Dillion Lowry</Copyright>
    <RepositoryUrl>https://github.com/DillionLowry/Rhizine</RepositoryUrl>
    <Description>Contains core interfaces, models, and services for use by other Rhizine packages.</Description>
    <PackageProjectUrl>https://github.com/DillionLowry/Rhizine</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ViewModels\Flyouts\**" />
    <Compile Remove="ViewModels\Pages\**" />
    <EmbeddedResource Remove="ViewModels\Flyouts\**" />
    <EmbeddedResource Remove="ViewModels\Pages\**" />
    <None Remove="ViewModels\Flyouts\**" />
    <None Remove="ViewModels\Pages\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Helpers\ToastNotificationActivationHandler.cs" />
    <Compile Remove="Services\EncryptionService.cs" />
    <Compile Remove="Services\IdentityService.cs" />
    <Compile Remove="Services\Interfaces\IPopupService.cs" />
    <Compile Remove="Services\Interfaces\ISystemService.cs" />
    <Compile Remove="Services\NavigationService.cs" />
    <Compile Remove="Services\PersistAndRestoreService.cs" />
    <Compile Remove="Services\PopupService.cs" />
    <Compile Remove="Services\ResilientDataService.cs" />
    <Compile Remove="Services\SystemService.cs" />
    <Compile Remove="ViewModels\ShellDialogViewModel.cs" />
    <Compile Remove="ViewModels\ShellViewModel.cs" />
    <Compile Remove="ViewModels\WaitPopupViewModel.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.4" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.1" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
  </ItemGroup>

</Project>
